### ISSUE TITLE
Read-only mode coming up with no Close button

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#222]
When we open a form in read-only mode and it shows the message that the form is locked by another user, it is displaying with no Close button. There was no error on the form that I could see, so I don't think it is related to an invalid XForm/record. So, we expected to see the Close button when opening in this view. I think this specific case was calling /instance/view with a load_warning paramater.

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9><page1><wh_y>1</wh_y></page1></demo-vitals-grid-v9>&instance_id=b&load_warning=Hey you&ecid=a" http://localhost:8005/oc/api/v1/instance/view
```

**Comment by MartijnR** [comment]
I wonder if it would actually be preferable to not pass the load_warning parameter to readonly views (and not 'lock').

**Comment by MartijnR** [comment]
Yes, that seems that would seem a lot better to me @pbowen-oc. What do you think?

**Comment by pbowen-oc** [comment]
I don't know that I follow. Can we discuss on Monday?

**Comment by MartijnR** [comment]
Sure!

> I wonder if it would actually be preferable to not pass the load_warning parameter to readonly views (and not 'lock' such a view).

**Comment by MartijnR** [comment]
OC redirects to readonly when record is locked, so message is shown to explain this redirect

**Comment by MartijnR** [comment]
Also in all views, we should not prevent submissions and remove buttons when a query or question is hidden

**Comment by MartijnR** [comment]
* [ ] enketo-core: make distinction between errors and warning (only goto issues)

**Comment by MartijnR** [comment]
So now goTo Errors and loadwarnings provide by OC, are not considered when blocking fieldsubmission and removing Complete/Close buttons.

**Comment by pbowen-oc** [comment]
We noticed an issue with the current implementation. While the form generally functions properly after the user dismisses the warning message, the "Saving..." and "All Changes Saved." messages never appear. Data is still submitted back to us as expected, but the user doesn't get any feedback on this

**Comment by MartijnR** [comment]
I believe you are referring to query-only views and submissions of queries.

**Comment by MartijnR** [comment]
Something else seems to be going on as well.

In note-only views, the fieldsubmissions are not taking place immediate after adding a query. Instead it seems they only submit when the Close button is clicked.

**Comment by MartijnR** [comment]
* [ ] remove clearedForSubmissions variable entirely. This was a bad implementation.
* [ ] instead disable the fieldSubmissionQueue centrally when a) form loads as readonly view, b) when an actual load error occurs (not goTo or API-requested loadwarning)

**Comment by MartijnR** [comment]
I finally figured out that the status update is deliberate disabled for note-only views. I'll enable it and still display the the 'review-only' message as well.

Wrt the above issue that fieldsubmissions are not immediately submitted, the fix is nearly done, but I'd consider it a bit risky, so it will need fairly thorough testing before deploying.

**Comment by pbowen-oc** [comment]
@MartijnR - The issue I was referring to was not specifically for note-only views. I observed it for edit mode of an existing record when I tried to open the form to an item that was currently irrelevant and null. This case shows an informational message to the user that the item they are trying to view is not currently displayed on the form. The form is intended to remain a functioning edit mode form in this case. From what I can tell, it is a functioning edit mode form, except that the Saving messages don't appear.

After the recent change to strictly handle the loading of forms with errors but prior to the initial fix for this issue, it was treated as an error form and did not allow any field submission at all.

**Comment by MartijnR** [comment]
Thanks, that makes sense actually, after learning about what I messed up in the code.

**Comment by MartijnR** [comment]
The absence of submission status messages had 2 causes.

1. Note-only views: this was deliberately disabled. I don't remember why.
2. Other views with go_to warning or loadWarning: bug that meant that no fieldsubmissions were taking place until the Close/Complete button is clicked

It is now fixed in latest master `1.77.1.oc-5`.

**Comment by pbowen-oc** [comment]
@MartijnR - We have not been able to deploy this update for testing yet. I am hoping we can get to it tomorrow. I will update you on the result of that once we can retry the below test.

We have just observed another issue that looks similar but does not seem to fall into the categories you outlined above. When we open this form as a new record, no errors/warnings are displayed, but the initial autosave is not occurring:

[calculations not submitting on load.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3522919/calculations.not.submitting.on.load.xml.txt)

There are a couple calculations that should be submitted back to us immediately when the form is first opened. However, those calculations are not submitted until either 1) the Close button is clicked or 2) a value of another item is manually entered.

Can you verify that this case was already covered by this issue's fix? If it is not, we will need a fix ASAP.

**Comment by pbowen-oc** [comment]
@MartijnR - Initial tests with the new build seems to indicate that the fix for this issue has resolved the calculation submission issue in my last comment. I'll update you if I find other problems remaining.

**Comment by MartijnR** [comment]
Oh great! Thanks.
