### ISSUE TITLE
Query Widget pops up under the visible part of the window for very tall items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#299]
If a form has a tall item (for example, an image map, vertical radio buttons with many options, or vertical radio buttons with image selection), clicking the query icon is causing the query widget is causing the item to scroll to the top of the screen and the query widget is not visible below the screen area. The user is also not able to scroll the screen to access the Query widget. 

Zooming out will make the Query widget visible.

In case like this, I think we need it to scroll the screen so that Query widget is visible (which will cut off the top of the item it belongs to).

Note that this occurs when opening the Query widget from the UI and also when opening directly to the query from outside of the form.

Maybe we should also allow the user to scroll the form when the Query widget is open.

**Comment by theywa** [comment]
Update the scroll to view position to Query Modal instead of Query button

**Comment by pbowen-oc** [comment]
@theywa - If the form item is not very tall, will it still scroll to the item?

If we always scroll to the query widget, then it would mean the parent item would be off the top of the screen and the user would not be able to clearly see which item the query widget belongs to.

**Comment by theywa** [comment]
@pbowen-oc - no, but the user can scrolling up the page from Query modal to check which item it belongs to(scrolling disabled outside the modal but working when pointer on it)

**Comment by MartijnR** [comment]
How about some algorithm like this:

1. check height of linked question
2. if taller > 300px (or some more clever clause that looks at window height and widget height), scroll to 200 px above the bottom of the linked question
3. otherwise, do the same as we currently do

**Comment by theywa** [comment]
sure I'll try to update the code, but it seems like the server_url(https://enketo-aggregate.appspot.com from [275](https://github.com/OpenClinica/enketo-express-oc/issues/275#issuecomment-569083531)) that used to get the form with Query button enabled is can't be accessed without the credentials anymore, is it possible to enable it again?

**Comment by MartijnR** [comment]
Done!

**Comment by theywa** [comment]
Thanks, code updated but window.scrollTo, window.scrollTop and jquery animate are not working, so I modify the logic to directly scroll to Query Modal if spare height between the window and the linked question is less than 50 px and set the block option on scrollIntoView to smooth(that will allow the user to see scrolling process to know which query modal it belong to).

**Comment by MartijnR** [comment]
For Martijn:
1. http://localhost:8005/single/fs/i/::YYpM
2. make window small
3. auto-add queries by uncommenting
4. open query for image map question on second page

**Comment by pbowen-oc** [comment]
We are still seeing this issue where the Query Widget opens in an inaccessible location:
![Annotation 2020-03-19 184041](https://user-images.githubusercontent.com/25179620/77121772-5d919900-6a12-11ea-9b4d-351af5b3257b.png)

**Comment by pbowen-oc** [comment]
Passed testing.
